# Configuration file for the 'cosmo-ghg-11km-test' case with COSMO-GHG

model: icon
constraint: gpu
ntasks_per_node: 12
restart_step: 6
startdate: 2018-01-01T00:00:00Z
hstart: 0
hstop: 12

meteo:
    dir: ./input/meteo
    prefix: ifs_
    nameformat: %Y%m%d%H.grb
    inc: 3

icontools_runjobs:
    - icontools_remap_ic_runjob.cfg
    - icontools_remap_00_lbc_runjob.cfg
    - icontools_remap_lbc_rest_runjob.cfg

input_files:
    radiation_grid_filename: ./input/icon/grid/VERIFY_DOM_DOM01.parent.nc
    dynamics_grid_filename: ['VERIFY_DOM_DOM01.nc', 'grid'],
    map_file_latbc: ['map_file.latbc', 'grid'],
    lateral_boundary_grid: ['lateral_boundary.grid.nc', 'grid'],
    extpar_filename: ['external_parameter_icon_VERIFY_DOM_DOM01_tiles.nc', 'grid'],
    cldopt_filename: ['rrtm_cldopt.nc', 'rad'],
    lrtm_filename: ['rrtmg_lw.nc', 'rad'],
    map_file_ana: ['map_file.ana', 'mapping'],

icon:
    binary_file: ./src/cosmo-ghg/cosmo/ACC/cosmo_gpu
    namelist_prefix: cosmo_INPUT_
    runjob_filename: cosmo_runjob.cfg
    compute_queue: normal
    walltime: "00:30:00"
    np_x: 6
    np_y: 4
    np_io: 0

