# Global ICON simulation initialized from ERA5 (IC only, no LBC).

workflow: icon-global-era5
constraint: EPYC_7H12
run_on: cpu
compute_queue: normal.4h
ntasks_per_node: 12
restart_step: PT6H
startdate: 2018-01-01T00:00:00Z
enddate:   2018-01-01T12:00:00Z

walltime:
  prepare_icon: "00:10:00"
  era5_ic:      "00:40:00"
  icon:         "00:30:00"

era5:
  dir: ./input/era5
  ml_filename:   "era5_ml_{ymd}.grib"  
  sfc_filename:  "era5_surf_{ymd}.grib"

era5_partab: ./cases/icon-euler-test/partab_era5_to_icon.txt
era5_ic_runjob_filename: era5_ic_runjob.cfg
inidata_prefix: "era5_init_R02B05_"
inidata_nameformat: "%Y%m%d%H"
inidata_filename_suffix: ".nc"

meteo:
  dir: ./input/meteo
  prefix: ifs_
  nameformat: "%Y%m%d%H"
  suffix: .grb
  inc: 3

input_files:
  dynamics_grid_filename:   ./input/icon/grid/iconR2B05-DOM01.nc
  extpar_filename:          ./input/icon/grid/extpar_iconR2B05-DOM01.nc
  lrtm_filename:            ./input/icon/rad/rrtmg_lw.nc
  cldopt_filename:          ./input/icon/rad/rrtm_cldopt.nc
  map_file_ana:             ./input/icon/mapping/map_file.ana

icon:
  binary_file: /cluster/work/climate/lroither/icon_c2sm/icon/bin/icon
  runjob_filename: icon_runjob.cfg
  np_tot: 96
  np_io: 1
  np_restart: 1
  np_prefetch: 0 
