# Configuration file for the 'icon-async-test' case with ICON

workflow: icon
constraint: EPYC_7H12
run_on: cpu
compute_queue: normal.4h
ntasks_per_node: 12
restart_step: PT6H
startdate: 2018-01-01T00:00:00Z
enddate: 2018-01-01T12:00:00Z

eccodes_dir: ./input/eccodes_definitions
iconremap_bin: ./ext/icontools/icontools/iconremap
iconsub_bin: ./ext/icontools/icontools/iconsub
latbc_filename: ifs_201801<d><h>_lbc.nc
inidata_filename: ifs_init_2018010100.nc
output_filename: NWP_LAM
filename_format: <output_filename>_DOM<physdom>_<ddhhmmss>
lateral_boundary_grid_order: lateral_boundary

walltime:
    prepare_icon: '00:10:00'
    icontools: '00:30:00'
    icon: '00:30:00'

meteo:
    dir: ./input/meteo
    prefix: ifs_
    nameformat: '%Y%m%d%H'
    suffix: .grb
    inc: 3

icontools_runjobs:
    - icontools_remap_ic_runjob.cfg
    - icontools_remap_00_lbc_runjob.cfg
    - icontools_remap_lbc_rest_runjob.cfg

input_files:
    radiation_grid_filename: ./input/icon/grid/VERIFY_DOM_DOM01.parent.nc
    dynamics_grid_filename: ./input/icon/grid/VERIFY_DOM_DOM01.nc
    map_file_latbc: ./input/icon/grid/map_file.latbc
    lateral_boundary_grid: ./input/icon/grid/lateral_boundary.grid.nc
    extpar_filename: ./input/icon/grid/external_parameter_icon_VERIFY_DOM_DOM01_tiles.nc
    cldopt_filename: ./input/icon/rad/rrtm_cldopt.nc
    lrtm_filename: ./input/icon/rad/rrtmg_lw.nc
    map_file_ana: ./input/icon/mapping/map_file.ana

icon:
    binary_file: ./ext/icon/bin/icon
    runjob_filename: icon_runjob.cfg
    np_tot: 96
    np_io: 1
    np_restart: 1
    np_prefetch: 1

