# Global ICON simulation initialized from ERA5 (IC only, no LBC).

workflow: icon-global-era5
constraint: EPYC_7H12
run_on: cpu
compute_queue: normal.4h
ntasks_per_node: 12
restart_step: PT6H
startdate: 2018-01-01T00:00:00Z
enddate:   2018-01-01T12:00:00Z
era5_partab: tables/partab_era5_to_icon.txt
era5_ic_runjob_filename: era5_ic_runjob.cfg
inidata_prefix: "era5_init_R02B06_"
inidata_nameformat: "%Y%m%d%H"
inidata_filename_suffix: ".nc"
output_filename: icon-test-euler
filename_format: <output_filename>_DOM<physdom>_<ddhhmmss>
lateral_boundary_grid_order: lateral_boundary

walltime:
  prepare_icon: "00:10:00"
  era5_ic:      "00:40:00"
  icon:         "00:30:00"

era5:
  dir: ./input/era5
  ml_filename:   "era5_ml_{ymd}.grib"  
  sfc_filename:  "era5_surf_{ymd}.grib"
  global_nudging: False

meteo:
  dir: ./input/meteo
  prefix: ifs_
  nameformat: "%Y%m%d%H"
  suffix: .grb
  inc: 3

input_files:
  dynamics_grid_filename:   ./input/icon/grid/icon_grid_0002_R02B06_G.nc
  extpar_filename:          ./input/icon/grid/icon_extpar_0002_R02B06_G.nc
  lrtm_filename:            /cluster/work/climate/icon_input/icon-model/release-2026.04-public/data/rrtmg_lw.nc
  cldopt_filename:          /cluster/work/climate/icon_input/icon-model/release-2026.04-public/data/ECHAM6_CldOptProps.nc
  map_file_ana:             /cluster/work/climate/icon_input/icon-model/release-2026.04-public/run/ana_varnames_map_file.txt

icon:
  binary_file: /cluster/work/climate/icon_input/icon-model/release-2026.04-public/bin/icon
  runjob_filename: icon_runjob.cfg
  np_tot: 96
  np_io: 1
  np_restart: 1
  np_prefetch: 0 
