# Configuration file for the 'icon-art-CTDAS' case with ICON

# From the `icon-wcp` environment:
# - spack install nco@4.9.0
# - spack install icontools@c2sm-master%gcc
# - spack install cdo

workflow: icon
constraint: gpu
run_on: cpu
compute_queue: normal
nodes: 2
ntasks_per_node: 4
startdate: 2018-01-01T00:00:00Z
enddate: 2018-12-31T23:59:59Z
restart_step: PT10D # = CTDAS cycle length

####### Tracer options
# The tracers XML file will be generated on-the-fly
tracers:
    TRCO2_A:
        oem_cat: "A-CO2, B-CO2, C-CO2, D-CO2, E-CO2, F1-CO2, F2-CO2, F3-CO2, F4-CO2, G-CO2, H-CO2, I-CO2, J-CO2, K-CO2, L-CO2"
        oem_vp:  "A-CO2, B-CO2, C-CO2, D-CO2, E-CO2, F1-CO2, F2-CO2, F3-CO2, F4-CO2, G-CO2, H-CO2, I-CO2, J-CO2, K-CO2, L-CO2"
        oem_tp:  "GNFR_A-CO2, GNFR_B-CO2, GNFR_C-CO2, GNFR_D-CO2, GNFR_A-CO2, GNFR_F-CO2, GNFR_F-CO2, GNFR_F-CO2, GNFR_F-CO2, GNFR_G-CO2, GNFR_H-CO2, GNFR_I-CO2, GNFR_J-CO2, GNFR_L-CO2, L-CO2"
    TRCO2_BG:
        init_name: "CO2"
    CO2_RA:
        oem_ftype: "resp"
    CO2_GPP:
        oem_ftype: "gpp"
    TRCO2_A-XXX:
        bg: "TRCO2_BG"
        ra: "CO2_RA"
        gpp: "CO2_GPP"
    biosource:
        oem_cat: "co2fire, allcropsource, allwoodsource, lakeriveremis, cflx"
        oem_vp:  "A-CO2,   A-CO2,         A-CO2,         A-CO2,         A-CO2"
        oem_tp:  "GNFR_A-CO2,   GNFR_A-CO2,         GNFR_A-CO2,         GNFR_A-CO2,         GNFR_A-CO2"
    biosink:
        oem_cat: "biofuelcropsource, biofuelwoodsource, mflx"
        oem_vp:  "A-CO2,             A-CO2,             A-CO2"
        oem_tp:  "GNFR_A-CO2,             GNFR_A-CO2,             GNFR_A-CO2"

####### CTDAS options.
# First of all, download https://git.wur.nl/ctdas/CTDAS/-/tree/ctdas-icon
# (i.e., CTDAS with the ctdas-icon branch).
# Execute `start_ctdas_icon.sh $SCRATCH ctdas_procchain`
# which will put the CTDAS files into $SCRATCH/ctdas_procchain.
# We will then 'patch' this CTDAS installation with the required files,
# - ctdas-icon.py [which runs CTDAS; and imports the following patched classes]:
    # - statevector class [which, ultimately, defines our ensemble members]
    # - observation operator (obsoperator) class [which, ultimately, runs the ICON scripts & post-processing sampler]
    # - observations class [which, ultimately, defines how to ingest the observations]
    # - optimizer class [which, ultimately, defines how to do localization]
# - rc-cteco2 file [which, ultimately, is how we pass general input like folder names etc to CTDAS]
# - rc-job file [which, ultimately, is the setup for CTDAS like lag times, etc.]
CTDAS:
    nlag: 2
    tracer: co2
    regions: basegrid # choose: basegrid or parentgrid
    nensembles: 186
    # nregions: # read from cells->regions file
    restart_init_time: 86400 # 1 day in seconds; using Michael Steiner's "overwriting" restart mechanism
    ctdas_cycle: 10 # days
    nboundaries: 8
    lambdas: # The first 16 lambdas must be the respiration and uptake ones [even if not relevant, e.g., for a CH4 simulation], followed by the oem_cat categories in the xml file, in order of appearance, but excluding any 
        - 1,1,1,1,1,1,1,1 # Respiration (Evergreen Forest, Deciduous Forest, Mixed Forest, Shrubland, Savanna, Cropland, Grassland, Urban/Other)
        - 1,1,1,1,1,1,1,1 # Uptake (E, D, M, S, SV, C, G, U)
        - 2,2,2,2,2,2,2,2,2,2,2,2,2,2,2 # Anthropogenic CO2 (ensemble tracer categories that are optimized)
    obs:
        # Run the 'authentification.ipynb' notebook to get access to ICOS and/or NASA Earthdata (OCO2) data
        fetch_ICOS: True
        ICOS_path: /capstor/scratch/cscs/ekoene/ICOS/
        fetch_OCO2: True
        OCO2_path: /capstor/scratch/cscs/ekoene/OCO2
    global_inputs:
        inventories:
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180102.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180112.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180122.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180201.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180211.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180221.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180303.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180313.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180323.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180402.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180412.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180422.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180502.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180512.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180522.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180601.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180611.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180621.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180701.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180711.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180721.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180731.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180810.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180820.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180830.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180909.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180919.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180929.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181009.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181019.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181029.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181108.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181118.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181128.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181208.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181218.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181228.nc
        grid:
            - /users/ekoene/CTDAS_inputs/icon_europe_DOM01.parent.nc
            - /users/ekoene/CTDAS_inputs/icon_europe_DOM01.nc
            - ERA5/lateral_boundary.grid.nc # This is guaranteed to exist due to the ERA5/CAMS preprocessing
        extpar:
            - /users/ekoene/CTDAS_inputs/icon_extpar_EriksGrid.nc
        VPRM:
            - /users/ekoene/CTDAS_inputs/VPRM_indices_ICON_datestr.nc
        OEM:
            - /capstor/scratch/cscs/ekoene/inventories/icon_with_tno_emissions/vertical_profiles.nc
            - /capstor/scratch/cscs/ekoene/inventories/icon_with_tno_emissions/hourofyear.nc
            # - /users/ekoene/CTDAS_inputs/vertical_profiles_t.nc
            # - /users/ekoene/CTDAS_inputs/hourofyear8784.nc


# # CTDAS ------------------------------------------------------------------------
# ctdas_restart = False
# ctdas_BG_run = False
# # CTDAS cycle length in days
# ctdas_cycle = int(restart_cycle_window / 60 / 60 / 24)
# ctdas_nlag = 2
# ctdas_tracer = 'co2'
# # CTDAS number of regions and cells->regions file
# ctdas_nreg_params = 21184
# ctdas_regionsfile = vprm_regions_synth_nc # <--- Create 
# # Number of boundaries, and boundaries mask/regions file
# ctdas_bg_params = 8
# # Number of ensemble members (make this consistent with your XML file!)
# ctdas_optimizer_nmembers = 180
# # CTDAS path
# ctdas_dir = '/scratch/snx3000/ekoene/ctdas-icon/exec'
# # Distance file from region to region (shape: [N_reg x N_reg]), for statevector localization
# ctdas_sv_distances = '/scratch/snx3000/ekoene/CTDAS_cells2cells.nc'
# # Distance file from region to stations (shape: [N_reg x N_obs]), for observation localization
# ctdas_op_loc_coeffs = '/scratch/snx3000/ekoene/cells2stations.nc'
# # Directory containing a file with all the observations
# ctdas_datadir = '/scratch/snx3000/ekoene/ICOS_extracted/2018/'
# # CTDAS localization setting
# ctdas_system_localization = 'spatial'
# # CTDAS statevector length for one window
# ctdas_nparameters = 2 * ctdas_nreg_params + 8  # 2 (A , VPRM) * ctdas_nreg_params + ctdas_bg_params
# # Extraction template
# ctdas_extract_template = '/scratch/snx3000/ekoene/processing-chain/cases/VPRM_EU_ERA5_22/extract_template_icos_EU'
# # ICON runscript template
# ctdas_ICON_template = '/scratch/snx3000/ekoene/processing-chain/cases/VPRM_EU_ERA5_22/runscript_template_restart_icos_EU'
# # Full path to SBATCH template that can submit extraction scripts
# ctdas_sbatch_extract_template = '/scratch/snx3000/ekoene/processing-chain/cases/VPRM_EU_ERA5_22/sbatch_extract_template'
# # Full path to possibly time-varying emissionsgrid (if not time-varying, supply a filename without {}!)
# ctdas_oae_grid = "/scratch/snx3000/ekoene/inventories/INV_{}.nc"
# ctdas_oae_grid_fname = '%Y%m%d'  # Specifies the naming scheme to use for the emission grids
# # Spinup time length
# # Restart file for the first simulation
# ctdas_first_restart_init = '/scratch/snx3000/ekoene/processing-chain/work/VPRM_EU_ERA5_22/2018010100_0_240/icon/output_INIT'
# # Number of vertical levels
# nvlev = 60
# # NOT NEEDED FOR ANYTHING, EXCEPT TO MAKE CTDAS RUN
# ctdas_obsoperator_home = '/scratch/snx3000/msteiner/ctdas_test/exec/da/rc/stilt'
# ctdas_obsoperator_rc = os.path.join(ctdas_obsoperator_home, 'stilt_0.rc')
# ctdas_regtype = 'olson19_oif30'

cdo_nco_cmd: |
    CLUSTER_NAME=todi uenv start icon-wcp --ignore-tty << 'EOF'
    . /capstor/scratch/cscs/ekoene/tmp/spack-c2sm/setup-env.sh /user-environment/
    spack load icontools cdo nco
    
cdo_nco_cmd_post: |
    EOF

eccodes_dir: ./input/eccodes_definitions
art_input_folder: ./input/icon-art-oem/ART

walltime:
    prepare_icon: '00:15:00'
    prepare_art_global: '00:10:00'
    icon: '00:05:00'
    prepare_CTDAS: '20:00:00'

meteo:
    nudging_step: 3
    fetch_era5: True
    interpolate_CAMS_to_ERA5: True
    url: https://cds-beta.climate.copernicus.eu/api
    key: 1c2e45b1-dd08-4bc4-90c8-15c06304ae69
    era5_splitjob: ICBC/icon_era5_splitfiles.sh
    era5_inijob: ICBC/icon_era5_inicond.sh
    era5_nudgingjob: ICBC/icon_era5_nudging.sh
    partab: mypartab

chem:
    nudging_step: 3
    fetch_CAMS: True
    url: https://ads-beta.atmosphere.copernicus.eu/api
    key: 1c2e45b1-dd08-4bc4-90c8-15c06304ae69
    cams_inijob: ICBC/icon_species_inicond.sh
    cams_nudgingjob: ICBC/icon_species_nudging.sh
    
input_files:
    radiation_grid_filename: /users/ekoene/CTDAS_inputs/icon_europe_DOM01.parent.nc
    dynamics_grid_filename: /users/ekoene/CTDAS_inputs/icon_europe_DOM01.nc
    extpar_filename: /users/ekoene/CTDAS_inputs/icon_extpar_EriksGrid.nc
    map_filename: ./cases/icon-art-CTDAS/map_file.ana
    wrapper_filename: ./cases/icon-art-CTDAS/wrapper_icon.sh

icon:
    executable: /capstor/scratch/cscs/ekoene/spack-c2sm/spack/opt/spack/linux-sles15-neoverse_v2/nvhpc-24.3/icon-develop-sytqk6o7h5y3imrsevsswc2inxaegbpx/bin/icon
    runjob_filename: ICON/ICON_template.job
#     # era5_inijob: icon_era5_inicond.sh
#     # era5_nudgingjob: icon_era5_nudging.sh
#     species_inijob: icon_species_inicond.sh
#     species_nudgingjob: icon_species_nudging.sh
#     output_writing_step: 6
#     compute_queue: normal
#     np_tot: 32
#     np_io: 3
#     np_restart: 1
#     np_prefetch: 1