# Configuration file for the 'icon-art-CTDAS' case with ICON

# From the `icon-wcp` environment:
# - spack install nco@4.9.0
# - spack install icontools@c2sm-master%gcc
# - spack install cdo

workflow: icon
constraint: gpu
run_on: cpu
compute_queue: normal
nodes: 2
ntasks_per_node: 4
startdate: 2018-01-01T00:00:00Z
enddate: 2018-12-31T23:59:59Z
restart_step: PT10D # = CTDAS cycle length

####### Tracer options
# The tracers XML file will be generated on-the-fly
tracers:
    TRCO2_A:
        oem_cat: "A-CO2, B-CO2, C-CO2, D-CO2, E-CO2, F1-CO2, F2-CO2, F3-CO2, F4-CO2, G-CO2, H-CO2, I-CO2, J-CO2, K-CO2, L-CO2"
        oem_vp:  "A-CO2, B-CO2, C-CO2, D-CO2, E-CO2, F1-CO2, F2-CO2, F3-CO2, F4-CO2, G-CO2, H-CO2, I-CO2, J-CO2, K-CO2, L-CO2"
        oem_tp:  "A-CO2, B-CO2, C-CO2, D-CO2, E-CO2, F1-CO2, F2-CO2, F3-CO2, F4-CO2, G-CO2, H-CO2, I-CO2, J-CO2, K-CO2, L-CO2"
    TRCO2_BG:
        init_name: "CO2"
    CO2_RA:
        oem_ftype: "resp"
    CO2_GPP:
        oem_ftype: "gpp"
    TRCO2_A-XXX:
        bg: "TRCO2_BG"
        ra: "CO2_RA"
        gpp: "CO2_GPP"
    biosource:
        oem_cat: "GFAS1, GFAS2, GFAS3, GFAS4, GFAS5, GFAS6, GFAS7, GFAS8, GFAS9, GFAS10, allcropsource, allwoodsource, lakeriveremis, cflx"
        oem_vp:  "L-CO2, L-CO2, L-CO2, L-CO2, L-CO2, L-CO2, L-CO2, L-CO2, L-CO2, L-CO2,   L-CO2,         L-CO2,         L-CO2,         L-CO2"
        oem_tp:  "GFAS1, GFAS2, GFAS3, GFAS4, GFAS5, GFAS6, GFAS7, GFAS8, GFAS9, GFAS10,  L-CO2,         L-CO2,         L-CO2,         L-CO2"
    biosink:
        oem_cat: "biofuelcropsource, biofuelwoodsource, mflx"
        oem_vp:  "L-CO2,             L-CO2,             L-CO2"
        oem_tp:  "L-CO2,             L-CO2,             L-CO2"
    EM_TRCO2_A:
        oem_cat: "A-CO2, B-CO2, C-CO2, D-CO2, E-CO2, F1-CO2, F2-CO2, F3-CO2, F4-CO2, G-CO2, H-CO2, I-CO2, J-CO2, K-CO2, L-CO2"
        oem_vp:  "A-CO2, B-CO2, C-CO2, D-CO2, E-CO2, F1-CO2, F2-CO2, F3-CO2, F4-CO2, G-CO2, H-CO2, I-CO2, J-CO2, K-CO2, L-CO2"
        oem_tp:  "A-CO2, B-CO2, C-CO2, D-CO2, E-CO2, F1-CO2, F2-CO2, F3-CO2, F4-CO2, G-CO2, H-CO2, I-CO2, J-CO2, K-CO2, L-CO2"
    EM_CO2_RA:
        oem_ftype: "resp"
    EM_CO2_GPP:
        oem_ftype: "gpp"
####### CTDAS options.
# First of all, do the following in your ~ (home) folder, e.g.,
# git clone -b ctdas-icon https://git.wur.nl/ctdas/CTDAS.git ~/ctdas-icon
# We will PATCH that code
# Execute `start_ctdas_icon.sh $SCRATCH ctdas_procchain`
# which will put the CTDAS files into $SCRATCH/ctdas_procchain.
# We will then 'patch' this CTDAS installation with the required files,
# - ctdas-icon.py [which runs CTDAS; and imports the following patched classes]:
    # - statevector class [which, ultimately, defines our ensemble members]
    # - observation operator (obsoperator) class [which, ultimately, runs the ICON scripts & post-processing sampler]
    # - observations class [which, ultimately, defines how to ingest the observations]
    # - optimizer class [which, ultimately, defines how to do localization]
# - rc-cteco2 file [which, ultimately, is how we pass general input like folder names etc to CTDAS]
# - rc-job file [which, ultimately, is the setup for CTDAS like lag times, etc.]
CTDAS:
    runthrough: True # If true, this makes the 'CTDAS' job run (1) CTDAS but also (2) a simulation for the full year without the ensemble members but with n_boundaries BG tracers
    nlag: 2
    tracer: co2
    regions: basegrid # choose: basegrid or parentgrid
    nensembles: 186
    # nregions: # read from cells->regions file
    restart_init_time: 86400 # 1 day in seconds; using Michael Steiner's "overwriting" restart mechanism
    ctdas_cycle: 10 # days
    ctdas_nlag: 2
    nboundaries: 8
    propagate_bg: True # If true, an additional ensemble member is created which just holds the background tracer
    lambdas: # The first 16 lambdas must be the respiration and uptake ones [even if not relevant, e.g., for a CH4 simulation], followed by the oem_cat categories in the xml file, in order of appearance, but excluding any 
        - 1,1,1,1,1,1,1,1 # Respiration (Evergreen Forest, Deciduous Forest, Mixed Forest, Shrubland, Savanna, Cropland, Grassland, Urban/Other)
        - 1,1,1,1,1,1,1,1 # Uptake (E, D, M, S, SV, C, G, U)
        - 2,2,2,2,2,2,2,2,2,2,2,2,2,2,2 # Anthropogenic CO2 (ensemble tracer categories that are optimized)
    obs:
        # Run the 'authentification.ipynb' notebook to get access to ICOS and/or NASA Earthdata (OCO2) data
        ICOS:
            fetch: False
            path: /capstor/scratch/cscs/ekoene/ICOS/
            c_offset:  2 # ppm
            mdm: # Based on the 'runthrough' simulation
                - Beromunster_212: 5.246687084978375 + c_offset
                - Bilsdale_248: 3.7267864090697658 + c_offset
                - Biscarrosse_47: 4.44391367284266 + c_offset
                - Cabauw_207: 4.556938758005444 + c_offset
                - Carnsore Point_14: 3.9379375857221026 + c_offset
                - Ersa_40: 5.097001363286457 + c_offset
                - Gartow_341: 4.34505600864283 + c_offset
                - Heidelberg_30: 7.653180633677891 + c_offset
                - Hohenpeissenberg_131: 4.500672670985617 + c_offset
                - Hyltemossa_150: 4.451277813256869 + c_offset
                - Ispra_100: 7.200474834686076 + c_offset
                - Jungfraujoch_13: 2.0936499868978484 + c_offset
                - Karlsruhe_200: 6.269164507580145 + c_offset
                - Kresin u Pacova_250: 4.779867829743723 + c_offset
                - Heathfield_100: 5.16261949284921 + c_offset
                - La Muela_80: 3.9377850799858414 + c_offset
                - Laegern-Hochwacht_32: 7.6073774299042185 + c_offset
                - Lindenberg_98: 4.975832792946022 + c_offset
                - Lutjewad_60: 4.7013604883358715 + c_offset
                - Monte Cimone_8: 3.010641066355188 + c_offset
                - Observatoire de Haute Provence_100: 4.222056466810487 + c_offset
                - Observatoire perenne de l'environnement_120: 5.5236885807122915 + c_offset
                - Pic du Midi_28: 2.0843713258172123 + c_offset
                - Plateau Rosa_10: 1.9979033074650259 + c_offset
                - Puy de Dome_10: 4.330821043481535 + c_offset
                - Ridge Hill_90: 4.100794768506457 + c_offset
                - Saclay_100: 6.1904467326367945 + c_offset
                - Schauinsland_12: 4.018460150933421 + c_offset
                - Tacolneston_185: 4.8551091246134215 + c_offset
                - Torfhaus_147: 4.4048914639305385 + c_offset
                - Trainou_180: 5.605470151137809 + c_offset
                - Weybourne_10: 5.239988261278576 + c_offset
                - Zugspitze_3: 2.5079204353773696 + c_offset
            mountain_stations: 
                - Jungfraujoch_13
                - Monte Cimone_8
                - Puy de Dome_10
                - Pic du Midi_28
                - Zugspitze_3
                - Hohenpeissenberg_131
                - Schauinsland_12
                - Plateau Rosa_10
        OCO2:
            fetch: True
            path: /capstor/scratch/cscs/ekoene/OCO2
        localization: 400 # km -- currently applies to ICOS and OCO2 observations equally
    global_inputs:
        inventories:
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180102.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180112.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180122.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180201.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180211.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180221.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180303.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180313.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180323.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180402.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180412.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180422.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180502.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180512.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180522.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180601.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180611.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180621.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180701.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180711.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180721.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180731.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180810.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180820.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180830.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180909.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180919.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20180929.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181009.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181019.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181029.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181108.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181118.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181128.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181208.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181218.nc
            - /capstor/scratch/cscs/ekoene/inventories/INV_20181228.nc
        grid:
            - /users/ekoene/CTDAS_inputs/icon_europe_DOM01.parent.nc
            - /users/ekoene/CTDAS_inputs/icon_europe_DOM01.nc
            - ERA5/lateral_boundary.grid.nc # This is guaranteed to exist due to the ERA5/CAMS preprocessing
        extpar:
            - /users/ekoene/CTDAS_inputs/icon_extpar_EriksGrid.nc
        VPRM:
            - /users/ekoene/CTDAS_inputs/VPRM_indices_ICON_datestr.nc
        OEM:
            - /capstor/scratch/cscs/ekoene/inventories/icon_with_tno_emissions/vertical_profiles.nc
            - /capstor/scratch/cscs/ekoene/inventories/icon_with_tno_emissions/hourofyear.nc
    ctdas_path: /users/ekoene/ctdas-icon
    ctdas_patch:
        templates: 
            - ctdas_patch/template.py 
            - ctdas_patch/template.rc
            - ctdas_patch/template.jb
        da/cyclecontrol: ctdas_patch/initexit_cteco2.py
        da/statevectors: ctdas_patch/statevector_baseclass_icos_cities.py
        da/observations: ctdas_patch/obs_class_ICOS_OCO2.py
        da/obsoperators: ctdas_patch/obsoperator_ICOS_OCO2.py
        da/optimizers: ctdas_patch/optimizer_baseclass_icos_cities.py
        da/pipelines: ctdas_patch/pipeline_icon.py
        da/platform: ctdas_patch/santis.py
        da/rc/cteco2: ctdas_patch/carbontracker_icon_oco2.rc
        da/tools/icon:
            - ctdas_patch/utilities.py
            - ctdas_patch/icon_helper.py
            - ctdas_patch/icon_sampler.py
    covariancematrix_definition: |
            Corr = np.array([[1,   0], # VPRM has a 100% error (remember, lambda VPRM=1 as set above)
                             [0, 0.5]]) # Anthropogenic has a 50% error (remember, lambda Anth=2 as set above)
            specific_length_bio = 300 # km
            specific_length_anth = 200 # km
            exp_factors_anth = np.exp(-distances / specific_length_anth)
            exp_factors_bio = np.exp(-distances / specific_length_bio)

            for ix, _ in enumerate(distances):
                for ic in range(Corr.shape[0]):
                    for ik in range(Corr.shape[1]):
                        idx = ix * categories + ic
                        exp_factor = exp_factors_anth[ix] if ic == 1 or ik == 1 else exp_factors_bio[ix]
                        covariancematrix[idx, ik:-n_bg_params:categories] = exp_factor * Corr[ic, ik]

            #set variances for the 8 background elements
            if n_bg_params>0:
                for iii in np.arange(n_bg_params):
                    covariancematrix[-n_bg_params + iii                    , -n_bg_params + iii] = 0.015 * 0.015  # 0.015 * 400 = 6 ppm stdev
                    covariancematrix[-n_bg_params + (iii + 1) % n_bg_params, -n_bg_params + iii] = 0.015 * 0.015 * 0.25 # Neighbouring entries
                    covariancematrix[-n_bg_params + (iii - 1) % n_bg_params, -n_bg_params + iii] = 0.015 * 0.015 * 0.25 # Neighbouring entries
    job_time: 10:00:00

cdo_nco_cmd: |
    uenv start icon-wcp --ignore-tty << 'EOF'
    . /capstor/scratch/cscs/ekoene/tmp/spack-c2sm/setup-env.sh /user-environment/
    spack load icontools cdo nco
    
cdo_nco_cmd_post: |
    EOF

eccodes_dir: ./input/eccodes_definitions
art_input_folder: ./input/icon-art-oem/ART

walltime:
    prepare_icon: '00:15:00'
    prepare_art_global: '00:10:00'
    icon: '00:05:00'
    prepare_CTDAS: '00:00:00'

meteo:
    nudging_step: 3
    fetch_era5: True
    url: https://cds-beta.climate.copernicus.eu/api
    key: 1c2e45b1-dd08-4bc4-90c8-15c06304ae69
    era5_splitjob: ICBC/icon_era5_splitfiles.sh
    era5_inijob: ICBC/icon_era5_inicond.sh
    era5_nudgingjob: ICBC/icon_era5_nudging.sh
    partab: mypartab

chem:
    nudging_step: 3
    fetch_CAMS: True
    url: https://ads-beta.atmosphere.copernicus.eu/api
    key: 1c2e45b1-dd08-4bc4-90c8-15c06304ae69
    cams_inijob: ICBC/icon_species_inicond.sh
    cams_nudgingjob: ICBC/icon_species_nudging.sh
    
input_files:
    radiation_grid_filename: /users/ekoene/CTDAS_inputs/icon_europe_DOM01.parent.nc
    dynamics_grid_filename: /users/ekoene/CTDAS_inputs/icon_europe_DOM01.nc
    extpar_filename: /users/ekoene/CTDAS_inputs/icon_extpar_EriksGrid.nc
    map_filename: ./cases/icon-art-CTDAS/map_file.ana
    wrapper_filename: ./cases/icon-art-CTDAS/wrapper_icon.sh

icon:
    executable: /capstor/scratch/cscs/ekoene/tmp/spack-c2sm/spack/opt/spack/linux-sles15-neoverse_v2/nvhpc-24.3/icon-develop-sytqk6o7h5y3imrsevsswc2inxaegbpx/bin/icon
    runjob_filename: ICON/ICON_template.job
#     # era5_inijob: icon_era5_inicond.sh
#     # era5_nudgingjob: icon_era5_nudging.sh
#     species_inijob: icon_species_inicond.sh
#     species_nudgingjob: icon_species_nudging.sh
#     output_writing_step: 6
#     compute_queue: normal
#     np_tot: 32
#     np_io: 3
#     np_restart: 1
#     np_prefetch: 1