#!/bin/bash -l
#SBATCH --uenv="icon-wcp/v1:rc4"
#SBATCH --job-name="{cfg.casename}_{cfg.startdate_sim_yyyymmddhh}_{cfg.forecasttime}"
#SBATCH --time=00:50:00
#SBATCH --account={cfg.compute_account}
#SBATCH --nodes={cfg.nodes}
#SBATCH --ntasks-per-node={cfg.ntasks_per_node}
#SBATCH --ntasks-per-core=1
#SBATCH --cpus-per-task=1
#SBATCH --partition={cfg.compute_queue}
#SBATCH --constraint={cfg.constraint}
#SBATCH --chdir={cfg.icon_work}

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

dtime=120  # Simulation time step in seconds
dt_rad=$(( 4 * dtime )) # Radiation time step in seconds
dt_conv=$(( 1 * dtime )) # Convection time step in seconds
dt_sso=$(( 2 * dtime )) # SSO time step in seconds
dt_gwd=$(( 2 * dtime )) # gravity wave drag time step in seconds

# ----------------------------------------------------------------------------
# create ICON master namelist
# ----------------------------------------------------------------------------

cat > icon_master.namelist << EOF
! master_nml: ----------------------------------------------------------------
&master_nml
 lrestart                   =                     .FALSE.        ! .TRUE.=current experiment is resumed
/

! master_model_nml: repeated for each model ----------------------------------
&master_model_nml
 model_type                  =                          1         ! identifies which component to run (atmosphere,ocean,...)
 model_name                  =                      "ATMO"        ! character string for naming this component.
 model_namelist_filename     =              "NAMELIST_NWP"        ! file name containing the model namelists
 model_min_rank              =                          1         ! start MPI rank for this model
 model_max_rank              =                      65536         ! end MPI rank for this model
 model_inc_rank              =                          1         ! stride of MPI ranks
/

! time_nml: specification of date and time------------------------------------
&time_nml
 ini_datetime_string         =      "{ini_restart_string}"        ! initial date and time of the simulation
 end_datetime_string         =      "{ini_restart_end_string}"        ! end date and time of the simulation 10T00
/
EOF

# ----------------------------------------------------------------------
# model namelists
# ----------------------------------------------------------------------

cat > NAMELIST_NWP << EOF
! parallel_nml: MPI parallelization -------------------------------------------
&parallel_nml
 nblocks_c                   =                          1
 nproma_sub                  =                        800         ! loop chunk length
 p_test_run                  =                     .FALSE.        ! .TRUE. means verification run for MPI parallelization
 num_io_procs                =                          1         ! number of I/O processors
 num_restart_procs           =                          0         ! number of restart processors
 num_prefetch_proc           =                          1         ! number of processors for LBC prefetching
 iorder_sendrecv             =                          3         ! sequence of MPI send/receive calls
/


! run_nml: general switches ---------------------------------------------------
&run_nml
 ltestcase                   =                     .FALSE.        ! real case run
 num_lev                     =                         60         ! number of full levels (atm.) for each domain
 lvert_nest                  =                     .FALSE.        ! no vertical nesting
 dtime                       =                    $(( dtime ))        ! timestep in seconds
 ldynamics                   =                      .TRUE.        ! compute adiabatic dynamic tendencies
 ltransport                  =                      .TRUE.        ! compute large-scale tracer transport
 ntracer                     =                          0         ! number of advected tracers
 iforcing                    =                          3         ! forcing of dynamics and transport by parameterized processes
 msg_level                   =                          2         ! detailed report during integration
 ltimer                      =                      .TRUE.        ! timer for monitoring the runtime of specific routines
 timers_level                =                         10         ! performance timer granularity
 check_uuid_gracefully       =                      .TRUE.        ! give only warnings for non-matching uuids
 output                      =                       "nml"        ! main switch for enabling/disabling components of the model output
 lart                        =                      .TRUE.        ! main switch for ART
 debug_check_level           =                          2
/

! art_nml: Aerosols and Reactive Trace gases extension-------------------------------------------------
&art_nml
 lart_chem                  =                        .TRUE.       ! enables chemistry
 lart_pntSrc                =                        .FALSE.       ! enables point sources
 lart_aerosol               =                        .FALSE.       ! main switch for the treatment of atmospheric aerosol
 lart_chemtracer            =                        .TRUE.       ! main switch for the treatment of chemical tracer
 lart_diag_out              =                        .TRUE.       !
 iart_seasalt               =                            0        ! enable seasalt
 iart_init_gas              =                            4        ! Test versus '4'
 cart_cheminit_file         = "{inifile_nc}" 
 cart_chemtracer_xml        = '{tracers_xml}'       ! path to xml file for passive tracers
 cart_cheminit_coord        = '{inifile_nc}'
 cart_cheminit_type         = 'ERA'
/

! oem_nml: online emission module ---------------------------------------------
&oemctrl_nml                                                                   
 gridded_emissions_nc        = '{emissionsgrid_nc}'
 vertical_profile_nc         = '{vertical_profile_nc}'
 hour_of_year_nc             = '{hour_of_year_nc}'
 ens_lambda_nc               = '{lambda_nc}'
 ens_reg_nc                  = '{lambda_regions_nc}'
 boundary_lambda_nc          = '{bg_lambda_nc}'
 boundary_regions_nc         = '{bg_lambda_regions_nc}'
 vegetation_indices_nc       = '{vprm_coeffs_nc}'
 chem_restart_nc             = '{restart_file}'
 restart_init_time           = {restart_init_time}
 vprm_par                    =  452.0801019142973, 356.9982743495175, 444.35135030708693, 483.71014017898636,  6.820000E+02,  549.8142194931744, 545.613483159301, 0.0E+00
 vprm_lambda                 = -0.1976385733575807, -0.16249650220700065, -0.15183296864822501, -0.12614291858843657, -1.141000E-01, -0.10418834453782252, -0.13114180960813507, 0.0E+00  
 vprm_alpha                  =  0.3002548628277834, 0.22150160044981743, 0.20130383953759856, 0.238064533552737,  4.900000E-03,  0.19239326299324863, 0.405695555089534, 0.0E+00  
 vprm_beta                   = 0.6884293574708447, 1.0916535677003347, 1.7074258216614222, 0.18946623368956772,  0.000000E+00,  0.17642838146641998, 0.41774465249044423, 0.0E+00  
 vprm_tmin                   =  0.0,  0.0,  0.0,  2.0,  2.0,  5.0,  2.0, 0.0
 vprm_tmax                   = 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 0.0
 vprm_topt                   = 20.0, 20.0, 20.0, 20.0, 20.0, 22.0, 18.0, 0.0
 vprm_tlow                   =  4.0,  0.0,  2.0,  4.0,  0.0,  0.0,  0.0, 0.0  
/


! diffusion_nml: horizontal (numerical) diffusion ----------------------------
&diffusion_nml
 lhdiff_vn                   =                      .TRUE.        ! diffusion on the horizontal wind field
 lhdiff_temp                 =                      .TRUE.        ! diffusion on the temperature field
 lhdiff_w                    =                      .TRUE.        ! diffusion on the vertical wind field
 hdiff_order                 =                          5         ! order of nabla operator for diffusion
 itype_vn_diffu              =                          1         ! reconstruction method used for Smagorinsky diffusion
 itype_t_diffu               =                          2         ! discretization of temperature diffusion
 hdiff_efdt_ratio            =                         24.0       ! ratio of e-folding time to time step 
 hdiff_smag_fac              =                          0.025     ! scaling factor for Smagorinsky diffusion
/

! dynamics_nml: dynamical core -----------------------------------------------
&dynamics_nml
 iequations                  =                          3         ! type of equations and prognostic variables
 divavg_cntrwgt              =                          0.50      ! weight of central cell for divergence averaging
 lcoriolis                   =                      .TRUE.        ! Coriolis force
/

! extpar_nml: external data --------------------------------------------------
&extpar_nml
 itopo                       =                          1             ! topography (0:analytical)
 extpar_filename             = '{cfg.input_files_scratch_extpar_filename}'        ! filename of external parameter input file
 n_iter_smooth_topo          =                         1,1            ! iterations of topography smoother
 hgtdiff_max_smooth_topo     =                        750.0, 750.0    ! see Namelist doc
 heightdiff_threshold        =                        2250.0, 1500.0  ! see Namelist doc
/

! initicon_nml: specify read-in of initial state ------------------------------
&initicon_nml
 init_mode               = 2
 lread_ana               = .false.
 ltile_coldstart         = .true.
 ltile_init              = .false.
 ifs2icon_filename       = '{inifile_nc}'
 ana_varnames_map_file   = '{cfg.input_files_scratch_map_filename}'
/

! grid_nml: horizontal grid --------------------------------------------------
&grid_nml
 dynamics_grid_filename      = "{cfg.input_files_scratch_dynamics_grid_filename}"  ! array of the grid filenames for the dycore
 radiation_grid_filename     = "{cfg.input_files_scratch_radiation_grid_filename}" ! array of the grid filenames for the radiation model
 dynamics_parent_grid_id     =                          0         ! array of the indexes of the parent grid filenames
 lredgrid_phys               =                      .TRUE.        ! .true.=radiation is calculated on a reduced grid
 lfeedback                   =                      .TRUE.        ! specifies if feedback to parent grid is performed
 l_limited_area              =                      .TRUE.        ! .TRUE. performs limited area run
 ifeedback_type              =                          2         ! feedback type (incremental/relaxation-based)
 start_time                  =                          0.        ! Time when a nested domain starts to be active [s]
/

! gridref_nml: grid refinement settings --------------------------------------
&gridref_nml
 denom_diffu_v               =                        150.        ! denominator for lateral boundary diffusion of velocity
/

! interpol_nml: settings for internal interpolation methods ------------------
&interpol_nml
 nudge_zone_width            =                         42         ! width of lateral boundary nudging zone
 support_baryctr_intp        =                     .FALSE.        ! barycentric interpolation support for output
 nudge_max_coeff             =                       0.069
 nudge_efold_width           =                        2.0
/


! io_nml: general switches for model I/O -------------------------------------
&io_nml
 itype_pres_msl              =                          5         ! method for computation of mean sea level pressure
 itype_rh                    =                          1         ! method for computation of relative humidity
 lmask_boundary              =                      .TRUE.        ! mask out interpolation zone in output
/

! limarea_nml: settings for limited area mode ---------------------------------
&limarea_nml
 itype_latbc                 =                          1         ! 1: time-dependent lateral boundary conditions
 dtime_latbc                 =                        10800         ! time difference between 2 consecutive boundary data
 latbc_boundary_grid         = "{latbc_boundary_grid_nc}"       ! Grid file defining the lateral boundary
 latbc_path                  = "{cfg.icon_input_icbc}" ! Absolute path to boundary data
 latbc_varnames_map_file     = "{cfg.input_files_scratch_map_filename}"
 latbc_filename              = "era5_nudge_<y><m><d><h>.nc" ! boundary data input filename
 init_latbc_from_fg          =                     .FALSE.        ! .TRUE.: take lbc for initial time from first guess
/

! lnd_nml: land scheme switches -----------------------------------------------
&lnd_nml
 ntiles                      =                          3         ! number of tiles
 nlev_snow                   =                          3         ! number of snow layers
 lmulti_snow                 =                      .FALSE.       ! .TRUE. for use of multi-layer snow model
 idiag_snowfrac              =                         20         ! type of snow-fraction diagnosis
 lsnowtile                   =                       .TRUE.       ! .TRUE.=consider snow-covered and snow-free separately
 itype_root                  =                          2         ! root density distribution
 itype_heatcond              =                          3         ! type of soil heat conductivity
 itype_lndtbl                =                          4         ! table for associating surface parameters
 itype_evsl                  =                          4         ! type of bare soil evaporation
 cwimax_ml                   =                      5.e-4         ! scaling parameter for max. interception storage
 c_soil                      =                       1.75         ! surface area density of the evaporative soil surface
 c_soil_urb                  =                        0.5         ! same for urban areas
 lseaice                     =                      .TRUE.        ! .TRUE. for use of sea-ice model
 llake                       =                      .TRUE.        ! .TRUE. for use of lake model
/

! nonhydrostatic_nml: nonhydrostatic model -----------------------------------
&nonhydrostatic_nml
 iadv_rhotheta               =                          2         ! advection method for rho and rhotheta
 ivctype                     =                          2         ! type of vertical coordinate
 itime_scheme                =                          4         ! time integration scheme
 ndyn_substeps               =                          5         ! number of dynamics steps per fast-physics step
 exner_expol                 =                          0.333     ! temporal extrapolation of Exner function
 vwind_offctr                =                          0.2       ! off-centering in vertical wind solver
 damp_height                 =                     12250.0        ! height at which Rayleigh damping of vertical wind starts 
 rayleigh_coeff              =                          1.5       ! Rayleigh damping coefficient
 divdamp_order               =                         24         ! order of divergence damping 
 divdamp_type                =                          3          ! type of divergence damping
 divdamp_fac                 =                          0.004     ! scaling factor for divergence damping
 igradp_method               =                          3         ! discretization of horizontal pressure gradient
 l_zdiffu_t                  =                      .TRUE.        ! specifies computation of Smagorinsky temperature diffusion
 thslp_zdiffu                =                          0.02      ! slope threshold (temperature diffusion)
 thhgtd_zdiffu               =                        125.0       ! threshold of height difference (temperature diffusion)
 htop_moist_proc             =                      22500.0       ! max. height for moist physics
 hbot_qvsubstep              =                      22500.0       ! height above which QV is advected with substepping scheme
/

! nwp_phy_nml: switches for the physics schemes ------------------------------
&nwp_phy_nml
 inwp_gscp                   =                          2         ! cloud microphysics and precipitation
 inwp_convection             =                          1         ! convection
 lshallowconv_only           =                      .FALSE.       ! only shallow convection
 inwp_radiation              =                          4         ! radiation
 inwp_cldcover               =                          1         ! cloud cover scheme for radiation
 inwp_turb                   =                          1         ! vertical diffusion and transfer
 inwp_satad                  =                          1         ! saturation adjustment
 inwp_sso                    =                          1         ! subgrid scale orographic drag
 inwp_gwd                    =                          0         ! non-orographic gravity wave drag
 inwp_surface                =                          1         ! surface scheme
 latm_above_top              =                      .TRUE.        ! take into account atmosphere above model top for radiation computation
 ldetrain_conv_prec          =                      .TRUE.
 efdt_min_raylfric           =                       7200.        ! minimum e-folding time of Rayleigh friction
 itype_z0                    =                          2         ! type of roughness length data
 icapdcycl                   =                          3         ! apply CAPE modification to improve diurnalcycle over tropical land
 icpl_aero_conv              =                          1         ! coupling between autoconversion and Tegen aerosol climatology
 icpl_aero_gscp              =                          1         ! coupling between autoconversion and Tegen aerosol climatology
 dt_rad                      =                   $((dt_rad))        ! time step for radiation in s
 dt_conv                     =                  $((dt_conv))        ! time step for convection in s (domain specific)
 dt_sso                      =                   $((dt_sso))        ! time step for SSO parameterization
 dt_gwd                      =                   $((dt_gwd))        ! time step for gravity wave drag parameterization
/

! nwp_tuning_nml: additional tuning parameters ----------------------------------
&nwp_tuning_nml
 itune_albedo                =                          1         ! reduced albedo (w.r.t. MODIS data) over Sahara
 tune_gkwake                 =                         1.8
 tune_gkdrag                 =                        0.0
 tune_minsnowfrac            =                        0.3
/

! radiation_nml: radiation scheme ---------------------------------------------
&radiation_nml
 ecrad_isolver               =                          2
 irad_o3                     =                          7         ! ozone climatology
 irad_aero                   =                          6         ! aerosols
 albedo_type                 =                          2         ! type of surface albedo
 vmr_co2                     =                    390.e-06
 vmr_ch4                     =                   1800.e-09
 vmr_n2o                     =                   322.0e-09
 vmr_o2                      =                     0.20946
 vmr_cfc11                   =                    240.e-12
 vmr_cfc12                   =                    532.e-12
 direct_albedo_water         =                           3
 albedo_whitecap             =                           1
 ecrad_data_path             =     '/capstor/scratch/cscs/nponomar/icon-kit/externals/ecrad/data'
/

! sleve_nml: vertical level specification -------------------------------------
&sleve_nml
 min_lay_thckn               =                         20.0       ! layer thickness of lowermost layer
 top_height                  =                      23000.0       ! height of model top
 stretch_fac                 =                          0.65      ! stretching factor to vary distribution of model levels
 decay_scale_1               =                       4000.0       ! decay scale of large-scale topography component
 decay_scale_2               =                       2500.0       ! decay scale of small-scale topography component
 decay_exp                   =                          1.2       ! exponent of decay function
 flat_height                 =                      16000.0       ! height above which the coordinate surfaces are flat
/

! transport_nml: tracer transport ---------------------------------------------
&transport_nml
 ivadv_tracer                =              3, 3, 3, 3, 3, 3      ! tracer specific method to compute vertical advection
 itype_hlimit                =              3, 4, 4, 4, 4, 4      ! type of limiter for horizontal transport
 ihadv_tracer                =             52, 2, 2, 2, 2, 2     ! tracer specific method to compute horizontal advection
 llsq_svd                    =                      .TRUE.        ! use SV decomposition for least squares design matrix
/

! turbdiff_nml: turbulent diffusion -------------------------------------------
&turbdiff_nml
 tkhmin                      =                          0.75      ! scaling factor for minimum vertical diffusion coefficient
 tkmmin                      =                          0.75      ! scaling factor for minimum vertical diffusion coefficient
 pat_len                     =                        750.0       ! effective length scale of thermal surface patterns
 c_diff                      =                          0.2       ! length scale factor for vertical diffusion of TKE
 rat_sea                     =                          0.8       ! controls laminar resistance for sea surface
 ltkesso                     =                        .TRUE.      ! consider TKE-production by sub-grid SSO wakes
 frcsmot                     =                          0.2       ! these 2 switches together apply vertical smoothing of the TKE source terms
 imode_frcsmot               =                            2       ! in the tropics (only), which reduces the moist bias in the tropical lower troposphere
 itype_sher                  =                            3       ! type of shear forcing used in turbulence
 ltkeshs                     =                        .TRUE.      ! include correction term for coarse grids in hor. shear production term
 a_hshr                      =                          2.0       ! length scale factor for separated horizontal shear mode
 icldm_turb                  =                            1       ! mode of cloud water representation in turbulence
 ldiff_qi                    =                        .TRUE.
/

! output_nml: specifies an output stream --------------------------------------
&output_nml
 filetype                    =                          4         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                         =                          1         ! write domain 1 only
 output_bounds               =        0., 10000000., 3600.        ! start, end, increment
 steps_per_file              =                          1         ! number of steps per file
 mode                        =                          1         ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last                =                      .TRUE.
 output_filename             =                    'ICON-ART-UNSTR'
 filename_format             =   '{output_directory}/<output_filename>_<datetime>' ! file name base
 steps_per_file_inclfirst    =                    .FALSE.
 output_grid                =                      .TRUE.
 remap                       =                          0         ! 1: remap to lat-lon grid
 !north_pole                  =                   -170.,40.       ! definition of north_pole for rotated lat-lon grid
 reg_lon_def                 =              -8.25,0.05,17.65       !
 reg_lat_def                 =               40.75,0.05,58.85       !
 ml_varlist                  =  'group:PBL_VARS',
                                'group:ATMO_ML_VARS',
                                'group:precip_vars',
                                'group:land_vars',
                                'group:nh_prog_vars',
                                'group:ART_CHEMISTRY',
                                'z_mc', 'z_ifc',
                                'topography_c',                            
                                'group:ART_PASSIVE',
                                'group:ART_AEROSOL'
/

! output_nml: specifies an output stream --------------------------------------
&output_nml
 filetype                    =                          4         ! output format: 2=GRIB2, 4=NETCDFv2
 dom                         =                          1         ! write domain 1 only
 output_bounds               =      {output_init}, 10000000., 604800.   ! start, end, increment 518400
 steps_per_file              =                          1         ! number of steps per file
 mode                        =                          1         ! 1: forecast mode (relative t-axis), 2: climate mode (absolute t-axis)
 include_last                =                      .TRUE.
 output_filename             =                    'ICON-ART-OEM-INIT'
 filename_format             = '{output_directory}/<output_filename>_<datetime>' ! file name base
 steps_per_file_inclfirst    =                    .FALSE.
 output_grid                =                      .TRUE.
 remap                       =                          0         ! 1: remap to lat-lon grid
 ml_varlist                  =     'group:ART_CHEMISTRY'
/
EOF


cp {cfg.icon_executable} icon
srun /capstor/scratch/cscs/ekoene/icon-kit/run/run_wrapper/alps_mch_gpu.sh ./icon