# Configuration file for the 'icon-art-full-chem-test' case with ICON

workflow: icon-art-full-chem
constraint: mc
run_on: cpu
compute_queue: normal
ntasks_per_node: 36
restart_step: PT6H
startdate: 2019-02-12T00:00:00Z
enddate: 2019-02-26T00:00:00Z

eccodes_dir: /users/icontest/pool/data/ICON/mch/eccodes_definitions
latbc_filename: LBC_<y><m><d><h>.nc
inidata_prefix: IC_
inidata_nameformat: '%Y%m%d%H'
inidata_filename_suffix: .nc
lbcdata_prefix: LBC_
lbcdata_nameformat: '%Y%m%d%H'
lbcdata_filename_suffix: .nc
output_filename: icon-full-chem-test
filename_format: <output_filename>_<ddhhmmss>
lateral_boundary_grid_order: lateral_boundary
art_input_folder: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/art

walltime:
    prepare_icon: '00:10:00'
    prepare_art_full_chem: '01:00:00'
    icon: '02:00:00'

meteo:
    dir: /scratch/snx3000/ckeller/proc_chain_data/input/meteo
    prefix: era5_
    nameformat: '%Y%m%d%H'
    suffix: .grb
    inc: 3

chem:
    dir: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/chem
    prefix: camchem_
    nameformat: '%Y%m%d%H'
    suffix: .nc
    inc: 3
    icbc_filename: camchem-20190212-20190226.nc
    ref_date: '2000-03-01 00:00:00'


input_files:
    radiation_grid_filename: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/grid/base_grid.nc
    #radiation_grid_filename: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/grid/icon_R03B07_DOM01.nc
    dynamics_grid_filename: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/grid/icon_R03B07_DOM01.nc
    #dynamics_grid_filename: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/grid/icon_R03B08_DOM02.nc
    map_file_latbc: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/grid/map_file.latbc
    lateral_boundary_grid: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/grid/lateral_boundary_DOM01.grid.nc
    #lateral_boundary_grid: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/grid/lateral_boundary_DOM02.grid.nc
    extpar_filename: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/grid/extpar_DOM01.nc
    #extpar_filename: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/grid/extpar_DOM02.nc
    cldopt_filename: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/rad/rrtm_cldopt.nc
    lrtm_filename: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/rad/rrtmg_lw.nc
    map_file_ana: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/mapping/map_file.ana
    meccatracer_xml_filename: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/xml/mecca_tracers.xml
    oem_gridded_emissions_nc: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/oem/oem_gridded_emissions.nc
    oem_vertical_profiles_nc: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/oem/vertical_profiles.nc
    oem_hourofday_nc: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/oem/hourofday.nc
    oem_dayofweek_nc: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/oem/dayofweek.nc
    oem_monthofyear_nc: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/oem/monthofyear.nc
    #oem_gridded_emissions_nc: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/oem/oem_gridded_emissions_DOM02.nc
    #oem_vertical_profiles_nc: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/oem/vertical_profiles_DOM02.nc
    #oem_hourofday_nc: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/oem/hourofday_DOM02.nc
    #oem_dayofweek_nc: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/oem/dayofweek_DOM02.nc
    #oem_monthofyear_nc: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/oem/monthofyear_DOM02.nc
    aerodyn_tracers: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/aerodyn/tracers_aerosol.xml
    aerodyn_modes: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/aerodyn/modes.xml
    aerodyn_coag: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/aerodyn/coagulate.xml
    aerodyn_emiss: /scratch/snx3000/ckeller/proc_chain_data/input/icon-art-full-chem/aerodyn/emiss.xml


icon:
    binary_file: /scratch/snx3000/ckeller/proc_chain_data/ext/icon-art/bin/icon
    runjob_filename: icon_runjob.cfg
    era5_icjob: icon_era5_ic.sh
    era5_lbcjob: icon_era5_lbc.sh
    chem_icjob: icon_camchem_ic.sh
    chem_lbcjob: icon_camchem_lbc.sh
    compute_queue: normal
    walltime: '02:00:00'
    np_tot: 32
    np_io: 3
    np_restart: 1
    np_prefetch: 1
    timestep: 120.

