#!/usr/bin/env bash
#SBATCH --account=em05
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=36
#SBATCH --cpus-per-task=1
#SBATCH --time=0:05:00
#SBATCH --output=ini.out

date=20180101
WORKDIR=${SCRATCH}/ARTcases4C2SM
myoutdir=${WORKDIR}/input/icbc

ulimit -s unlimited

# SETTINGS: DIRECTORIES AND INPUT/OUTPUT FILE NAMES --------------------------

# directory containing DWD icon tools binaries
export ICONTOOLS_DIR=/users/msteiner/dwd_icon_tools_old/icontools

# file name of limited-area (target) grid
export LOCALGRID=${WORKDIR}/input/grids/testcase_DOM01.nc

# directory and filename of boundary file
export DATADIR=/store/empa/em05/dbrunner/icon-art/icbc

# file name of input grid, for IFS this is the boundary data file
INGRID=${DATADIR}/cams_gqpe_${date}_00.grb

# directory containing data files which shall be mapped to limited-area grid
DATAFILELIST=$(find ${DATADIR}/cams_gqpe_${date}_00.grb)

# output directory for extracted boundary data
export OUTDIR=$myoutdir #/remaped

#-----------------------------------------------------------------------------

BINARY_REMAP=iconremap
MPIEXE="srun -n 1"

#-----------------------------------------------------------------------------
# Remap inital data onto local (limited-area) grid
#-----------------------------------------------------------------------------

mkdir -p ${OUTDIR}
cd ${OUTDIR}
echo "This is where we are running the job ...."
pwd

cat > NAMELIST_ICONREMAP_FIELDS << EOF
!
&input_field_nml  ! ch4
 inputname      = "ch4"
 outputname     = "CH4_BG"
 code           = 255
 intp_method = 3
/
&input_field_nml  ! co2
 inputname      = "co2"
 outputname     = "CO2_BG"
 code           = 255
 intp_method = 3
/
&input_field_nml  ! co
 inputname      = "co"
 outputname     = "CO_BG"
 code           = 255
 intp_method = 3
/
&input_field_nml !aps
 inputname      = "lnsp"
 outputname     = "LNPS"
 code           = 152
 intp_method = 3
/
&input_field_nml  ! temperature
 inputname      = "T"
 outputname     = "T"
 code           = 130
 intp_method = 3
/
&input_field_nml  ! specific humidity
 inputname      = "q"
 outputname     = "QV"
 code           = 133
 intp_method = 3
/
EOF

#-----------------------------------------------------------------------------
# loop over file list:

echo "DATAFILELIST is ${DATAFILELIST}"
for datafilename in ${DATAFILELIST} ; do

  datafile="${datafilename##*/}"  # get filename without path
  outdatafile=${datafile%.*}      # get filename without suffix

# create ICON master namelist
# ------------------------
# For a complete list see Namelist_overview and Namelist_overview.pdf

  cat > NAMELIST_ICONREMAP << EOF
&remap_nml
 in_grid_filename  = '${INGRID}'
 in_filename       = '${DATADIR}/${datafile}'
 in_type           = 1
 out_grid_filename = '${LOCALGRID}'
 out_filename      = '${OUTDIR}/${outdatafile}.nc'
 out_type          = 2
 out_filetype      = 4
 l_have3dbuffer    = .false.
/
EOF

${MPIEXE} ${ICONTOOLS_DIR}/${BINARY_REMAP} \
            -vvvvv -q --remap_nml NAMELIST_ICONREMAP                         \
            --input_field_nml NAMELIST_ICONREMAP_FIELDS 2>&1

done

#-----------------------------------------------------------------------------
# clean-up

rm -f ncstorage.tmp*
rm -f nml.log  NAMELIST_SUB NAMELIST_ICONREMAP NAMELIST_ICONREMAP_FIELDS

#-----------------------------------------------------------------------------
exit
#-----------------------------------------------------------------------------
