#!/usr/bin/env bash
#SBATCH --account=em05
#SBATCH --partition=normal
#SBATCH --time=1:10:00
#SBATCH --constraint=mc
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=36
#SBATCH --cpus-per-task=1
#SBATCH --output=lbc_chem2.out

# Export some variables
export ECCODES_DEFINITION_PATH=/users/msteiner/eccodes_definitions/definitions.edzw-2.12.5-2:/store/empa/em05/easybuild/software/ecCodes/2.12.5-CrayGNU-19.10/share/eccodes/definitions
export GRIB_DEFINITION_PATH=/users/jenkins/install/libgrib_api/v1.20.0.2/cray/cosmo_definitions/:/users/jenkins/install/libgrib_api/v1.20.0.2/cray/share/grib_api/definitions:$GRIB_DEFINITION_PATH


date=20180101
WORKDIR=${SCRATCH}/ARTcases4C2SM
myoutdir=${WORKDIR}/input/icbc

ulimit -s unlimited

# SETTINGS: DIRECTORIES AND INPUT/OUTPUT FILE NAMES --------------------------

# directory containing DWD icon tools binaries
export ICONTOOLS_DIR=/users/msteiner/dwd_icon_tools_old/icontools

# file name of input grid, for IFS this is the boundary data file
export INGRID=/store/empa/em05/dbrunner/icon-art/icbc/cams_gqpe_${date}_00.grb

# file name of limited-area (target) grid
export LOCALGRID=${WORKDIR}/input/grids/VERIFY_DOM_DOM01.nc

# directory and filename of boundary file
export DATADIR=/store/empa/em05/dbrunner/icon-art/icbc

# directory where auxgrid will be
export AUXDIR=${WORKDIR}/input/icbc

# directory containing data files which shall be mapped to limited-area grid
DATAFILELIST=$(find ${DATADIR}/cams_gqpe_2018010[1-2]*.grb)

# output directory for extracted boundary data
export OUTDIR=$myoutdir

#-----------------------------------------------------------------------------

BINARY_ICONSUB=iconsub
BINARY_REMAP=iconremap
MPIEXE=" srun -n 1"

# grid file defining the lateral boundary
AUXGRID="lateral_boundary"

#-----------------------------------------------------------------------------
# PART I: Create auxiliary grid file which contains only the cells of the 
#         boundary zone.
#-----------------------------------------------------------------------------

#mkdir -p ${OUTDIR}
cd ${OUTDIR}
echo "This is where we are running the job ...."
pwd

cat > NAMELIST_ICONSUB_$date << EOF_1
&iconsub_nml
  grid_filename    = '${LOCALGRID}',
  output_type      = 4,
  lwrite_grid      = .FALSE.,
/
&subarea_nml
  ORDER            = "${AUXDIRDIR}/${AUXGRID}",
  grf_info_file    = '${LOCALGRID}',
  min_refin_c_ctrl = 1
  max_refin_c_ctrl = 14
/
EOF_1

#${MPIEXE}  ${ICONTOOLS_DIR}/${BINARY_ICONSUB} \
#               --nml NAMELIST_ICONSUB_$date 2>&1

#-----------------------------------------------------------------------------
# PART II: Extract boundary data
#-----------------------------------------------------------------------------

rm -f ncstorage.tmp_lbc_${date}*

set +x
cat > NAMELIST_ICONREMAP_FIELDS_$date << EOF
!
&input_field_nml  ! ch4
 inputname      = "ch4"
 outputname     = "CH4"
 code           = 255
 intp_method = 3
/
&input_field_nml  ! co2
 inputname      = "co2"
 outputname     = "CO2"
 code           = 255
 intp_method = 3
/
&input_field_nml  ! co
 inputname      = "co"
 outputname     = "CO" 
 code           = 255
 intp_method = 3
/
&input_field_nml  ! specific humidity
 inputname      = "q"
 outputname     = "QV" 
 code           = 133
 intp_method = 3
/
EOF

#-----------------------------------------------------------------------------
# loop over file list:

echo "DATAFILELIST is ${DATAFILELIST}"
for datafilename in ${DATAFILELIST} ; do

	datafile="${datafilename##*/}"  # get filename without path
	outdatafile=${datafile%.*}      # get filename without suffix

	cat > NAMELIST_ICONREMAP_lbc_$date << EOF_2C
&remap_nml
 in_grid_filename  = '${INGRID}'
 in_filename       = '${DATADIR}/${datafile}'
 in_type           = 1
 out_grid_filename = '${AUXDIR}/${AUXGRID}.grid.nc'
 out_filename      = '${OUTDIR}/${outdatafile}_lbc.nc'
 out_type          = 2
 out_filetype      = 4
 l_have3dbuffer    = .false.
! ncstorage_file    = "ncstorage.tmp_lbc_${date}"
/
EOF_2C

${MPIEXE} ${ICONTOOLS_DIR}/${BINARY_REMAP} -q \
            --remap_nml NAMELIST_ICONREMAP_lbc_$date                           \
            --input_field_nml NAMELIST_ICONREMAP_FIELDS_$date 2>&1

done

#-----------------------------------------------------------------------------
# clean-up

#rm -f ncstorage.tmp_lbc_${date}*
rm -f nml.log  
rm -f NAMELIST_ICONSUB_$date NAMELIST_ICONREMAP_lbc_$date NAMELIST_ICONREMAP_FIELDS_$date

#-----------------------------------------------------------------------------
exit
#-----------------------------------------------------------------------------

