#!/bin/tcsh -x

set datapath=../input/icbc

foreach day (01 02)

foreach hr (00 03 06 09 12 15 18 21)

cdo merge ${datapath}/ifs_201801${day}${hr}_lbc.nc ${datapath}/cams_gqpe_201801${day}_${hr}_lbc.nc ${datapath}/ifs_201801${day}${hr}_lbc.nc

end

end
