# Configuration file for the 'icon-art-oem-test' case with ICON

workflow: icon-art-oem
constraint: gpu
run_on: cpu
compute_queue: normal
ntasks_per_node: 12
restart_step: PT6H
startdate: 2018-01-01T00:00:00Z
enddate: 2018-01-01T12:00:00Z

eccodes_dir: ./input/eccodes_definitions
iconremap_bin: ./ext/icontools/icontools/iconremap
iconsub_bin: ./ext/icontools/icontools/iconsub
latbc_filename: ifs_<y><m><d><h>_lbc.nc
inidata_prefix: ifs_init_
inidata_nameformat: '%Y%m%d%H'
inidata_filename_suffix: .nc
output_filename: icon-art-oem-test
filename_format: <output_filename>_DOM<physdom>_<ddhhmmss>
lateral_boundary_grid_order: lateral_boundary
art_input_folder: ./input/icon-art-oem/ART

walltime:
    prepare_icon: '00:10:00'
    icontools: '00:30:00'
    prepare_art: '00:10:00'
    prepare_art_oem: '00:10:00'
    icon: '00:30:00'

meteo:
    dir: ./input/meteo
    prefix: ifs_
    nameformat: '%Y%m%d%H'
    suffix: .grb
    inc: 3

chem:
    dir: ./input/icon-art-oem/chem
    prefix: cams_gqpe_
    nameformat: '%Y%m%d_%H'
    suffix: .grb
    inc: 3
    remap_tracers:
        CH4_BG: TRCH4_chemtr

icontools_runjobs:
    - icontools_remap_ic_runjob.cfg
    - icontools_remap_00_lbc_runjob.cfg
    - icontools_remap_lbc_rest_runjob.cfg
    - icontools_remap_ic_chem_runjob.cfg
    - icontools_remap_lbc_chem_runjob.cfg

input_files:
    radiation_grid_filename: ./input/icon-art-oem/grid/testcase_DOM01.parent.nc
    dynamics_grid_filename: ./input/icon-art-oem/grid/testcase_DOM01.nc
    map_file_latbc: ./input/icon-art-oem/grid/map_file.latbc
    lateral_boundary_grid: ./input/icon-art-oem/grid/lateral_boundary.grid.nc
    extpar_filename: ./input/icon-art-oem/grid/external_parameter_icon_testcase_DOM01_tiles.nc
    cldopt_filename: ./input/icon-art-oem/rad/rrtm_cldopt.nc
    lrtm_filename: ./input/icon-art-oem/rad/rrtmg_lw.nc
    map_file_ana: ./input/icon-art-oem/mapping/map_file.ana
    chemtracer_xml_filename: ./input/icon-art-oem/XML/tracers_oh_pntsrc.xml
    pntSrc_xml_filename: ./input/icon-art-oem/XML/pntSrc_example.xml
    oem_gridded_emissions_nc: ./input/icon-art-oem/OEM/tno_3cat.nc
    oem_vertical_profiles_nc: ./input/icon-art-oem/OEM/vertical_profiles.nc
    oem_hourofday_nc: ./input/icon-art-oem/OEM/hourofday.nc
    oem_dayofweek_nc: ./input/icon-art-oem/OEM/dayofweek.nc
    oem_monthofyear_nc: ./input/icon-art-oem/OEM/monthofyear.nc

icon:
    binary_file: ./ext/icon-art/bin/icon
    runjob_filename: icon_runjob.cfg
    compute_queue: normal
    walltime: '00:10:00'
    np_tot: 8
    np_io: 1
    np_restart: 1
    np_prefetch: 1

