pipeline {
    environment {
       EMAIL_TO_1 = 'michael.jaehn@c2sm.ethz.ch'
    }
    agent {
        node {
            label 'daint'
        }
    }
    stages {
        stage('Setup miniconda') {
            environment {
                PATH = "${WORKSPACE}/miniconda/bin:$PATH"
            }
            steps {
                sh 'wget -O ${WORKSPACE}/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh'
                sh 'rm -fr ${WORKSPACE}/miniconda'
                sh 'bash miniconda.sh -b -p $WORKSPACE/miniconda'
                sh 'conda config --set always_yes yes --set changeps1 no'
                sh 'conda config --add channels conda-forge'
                sh 'conda update -n base -c defaults conda'
                sh 'conda env create -f env/environment.yml'
                sh '''source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                    conda activate proc-chain
                    conda deactivate
                    rm miniconda.sh'''
            }
            post {
                failure {
                    echo 'Cleaning up workspace'
                    deleteDir()
                }
            }
        }
        stage('Setup spack') {
            steps {
                sh './jenkins/scripts/setup-spack.sh'
            }
            post {
                failure {
                    echo 'Cleaning up workspace'
                    deleteDir()
                }
            }
        }
        stage('Preparation') {
            parallel {
                stage('Get data') {
                    steps {
                        sh './jenkins/scripts/get_data.sh'
                    }
                    post {
                        failure {
                            echo 'Cleaning up workspace'
                            deleteDir()
                        }
                    }
                }
                stage('Build int2lm') {
                    steps {
                        sh '''source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                        conda activate proc-chain
                        ./jenkins/scripts/build_int2lm.sh'''
                    }
                    post {
                        failure {
                            echo 'Cleaning up workspace'
                            deleteDir()
                        }
                    }
                }
                stage('Build int2lm') {
                    steps {
                        sh '''source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                        conda activate proc-chain
                        ./jenkins/scripts/build_int2lm.sh'''
                    }
                    post {
                        failure {
                            echo 'Cleaning up workspace'
                            deleteDir()
                        }
                    }
                }
                stage('Build COSMO-GHG') {
                    steps {
                        sh '''source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                        conda activate proc-chain
                        ./jenkins/scripts/build_cosmo-ghg.sh'''
                    }
                    post {
                        failure {
                            echo 'Cleaning up workspace'
                            deleteDir()
                        }
                    }
                }
                stage('Build ICON') {
                    steps {
                        sh '''source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                        conda activate proc-chain
                        ./jenkins/scripts/build_icon.sh'''
                    }
                    post {
                        failure {
                            echo 'Cleaning up workspace'
                            deleteDir()
                        }
                    }
                }
            }
        }
        stage('Test COSMO-GHG') {
            environment {
                PATH = "${WORKSPACE}/miniconda/bin:$PATH"
            }
            steps {
                sh '''source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                conda activate proc-chain
                . ${WORKSPACE}/src/spack-c2sm/setup-env.sh
                python run_chain.py cosmo-ghg-11km-test 2015-01-01 0 24 -f'''
            }
            post {
                failure {
                    echo 'Cleaning up workspace'
                    deleteDir()
                }
            }
        }
        stage('Test ICON') {
            environment {
                PATH = "${WORKSPACE}/miniconda/bin:$PATH"
            }
            steps {
                sh '''source ${WORKSPACE}/miniconda/etc/profile.d/conda.sh
                conda activate proc-chain
                . ${WORKSPACE}/src/spack-c2sm/setup-env.sh
                python run_chain.py icon-test 2018-01-01 0 24 -j prepare_data icon -f'''
            }                     
            post {
                failure {
                    echo 'Cleaning up workspace'
                    deleteDir()
                }
            }
        }
    }
    post {
        always{
            echo 'Cleaning up workspace'
                deleteDir()
        }
    }
}
