pipeline {
    environment {
       EMAIL_TO_1 = 'michael.jaehn@c2sm.ethz.ch'
    }
    agent {
        node {
            label 'euler'
        }
    }
    stages {
        stage('Preparation') {
            parallel {
                stage('Setup env') {
                    environment {
                        PATH = "${WORKSPACE}/miniforge/bin:$PATH"
                    }
                    steps {
                        ./jenkins/scripts/setup_env.sh --pip
                    }
                    post {
                        failure {
                            echo 'Cleaning up workspace'
                            deleteDir()
                        }
                    }
                }
                stage('Get data') {
                    steps {
                        sh './jenkins/scripts/get_data.sh'
                    }
                    post {
                        failure {
                            echo 'Cleaning up workspace'
                            deleteDir()
                        }
                    }
                }
                stage('Build ICON') {
                    steps {
                        sh './jenkins/scripts/build_icon.sh'
                    }
                    post {
                        failure {
                            echo 'Cleaning up workspace'
                            deleteDir()
                        }
                    }
                }
            }
        }
        stage('Test ICON') {
            environment {
                PATH = "${WORKSPACE}/miniconda/bin:$PATH"
            }
            steps {
                sh 'source "$WORKSPACE/venv/bin/activate"'
                sh './jenkins/scripts/test_icon.sh'
            }                     
            post {
                failure {
                    echo 'Cleaning up workspace'
                    deleteDir()
                }
            }
        }
    }
    post {
        always{
            echo 'Cleaning up workspace'
                deleteDir()
        }
        failure {
            mail to: "${env.EMAIL_TO_1}",
            subject: "Jenkins Pipeline Failed: ${currentBuild.fullDisplayName}",
            body: """The Jenkins pipeline ${currentBuild.fullDisplayName} has failed.
		
                View the build: ${env.BUILD_URL}
                """
        }
    }
}
