# Configuration file for the 'icon-art-global-test' case with ICON

workflow: icon-art-global
is_async: True
constraint: gpu
run_on: cpu
compute_queue: normal
ntasks_per_node: 12
restart_step: PT6H
startdate: 2018-01-01T00:00:00Z
enddate: 2018-01-01T12:00:00Z

eccodes_dir: ./input/eccodes_definitions
iconremap_bin: iconremap
iconsub_bin: iconsub
latbc_filename: ifs_<y><m><d><h>_lbc.nc
inidata_prefix: ifs_init_
inidata_nameformat: '%Y%m%d%H'
inidata_filename_suffix: .nc
output_filename: icon-art-global-test
filename_format: <output_filename>_DOM<physdom>_<ddhhmmss>
lateral_boundary_grid_order: lateral_boundary
art_input_folder: ./input/icon-art-global/art

species_inicond: True
species2restart:
    - TROH
species_global_nudging: False
species2nudge: []
nudging_step: 6

era5:
    inicond: False
    global_nudging: False

meteo:
    dir: ./input/meteo
    prefix: ifs_
    nameformat: '%Y%m%d%H'
    suffix: .grb
    inc: 3

chem:
    dir: ./input/icon-art-global/chem
    prefix: cams_gqpe_
    nameformat: '%Y%m%d_%H'
    suffix: .grb
    inc: 3

input_files:
    inicond_filename: ./input/icon-art-global/icbc/era2icon_R2B03_2022060200.nc
    map_file_nudging: ./input/icon-art-global/icbc/map_file.nudging
    radiation_grid_filename: ./input/icon-art-global/grid/iconR2B03-DOM01.nc
    dynamics_grid_filename: ./input/icon-art-global/grid/iconR2B03-DOM01.nc
    extpar_filename: ./input/icon-art-global/grid/extpar_iconR2B03-DOM01.nc
    cldopt_filename: ./input/icon-art-global/rad/ECHAM6_CldOptProps.nc
    lrtm_filename: ./input/icon-art-global/rad/rrtmg_lw.nc
    oh_molec_filename: ./input/icon-art-global/chemistry/oh_gcp2022_icongrid.nc
    chemtracer_xml_filename: ./input/icon-art-global/config/tracers.xml
    pntSrc_xml_filename: ./input/icon-art-global/config/point-sources.xml

icon:
    binary_file: ./ext/icon-art/bin/icon
    runjob_filename: icon_runjob.cfg
    era5_inijob: icon_era5_inicond.sh
    era5_nudgingjob: icon_era5_nudging.sh
    species_inijob: icon_species_inicond.sh
    species_nudgingjob: icon_species_nudging.sh
    output_writing_step: 6
    compute_queue: normal
    walltime: '00:10:00'
    np_tot: 4
    np_io: 1
    np_restart: 1
    np_prefetch: 1
