name: proc-chain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cdo
  - nco
  - netcdf4
  - numpy
  - f90nml
  - cartopy
  - matplotlib
  - scipy
  - pillow
  - xarray
  - cdsapi
  - sphinx
  - sphinx_rtd_theme
  - sphinx-copybutton
